language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra-android-support
    - sys-img-armeabi-v7a-android-19
env:
  matrix:
    - ANDROID_SDKS=android-19 ANDROID_TARGET=android-19

install:
  - cd example
before_script:
  - npm install -g grunt-cli
  - npm install
script: grunt
